### ISSUE TITLE
data[feat] = lbe.fit_transform(data[feat]) 会报错

### ISSUE THREAD

**Issue by PengboLiu** [liuchenailq/zhihu-baseline#1]
报错如下：
Traceback (most recent call last):
  File "/home/pengboliu/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py", line 105, in _encode
    res = _encode_python(values, uniques, encode)
  File "/home/pengboliu/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py", line 59, in _encode_python
    uniques = sorted(set(values))
TypeError: '<' not supported between instances of 'str' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pengboliu/workspace/Windows/zhihu/deepfm.py", line 77, in <module>
    data[feat] = lbe.fit_transform(data[feat])
  File "/home/pengboliu/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py", line 236, in fit_transform
    self.classes_, y = _encode(y, encode=True)
  File "/home/pengboliu/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py", line 107, in _encode
    raise TypeError("argument must be a string or number")
TypeError: argument must be a string or number

**Comment by liuchenailq** [comment]
这个问题可能是同一个类别特征既有int和str,你可以先将类别特征列强制转为str。
data[col].astype(str)
试下吧

**Comment by PengboLiu** [comment]
> 这个问题可能是同一个类别特征既有int和str,你可以先将类别特征列强制转为str。
> data[col].astype(str)
> 试下吧

好的 谢谢。
topic2index.pick 是需要自己创建吗？没看到生成此文件的函数

**Comment by liuchenailq** [comment]
对，这些操作都是NLP的常规操作。
1.建立词汇编码索引（从1开始编码）
2.每个样本生成maxlen的词序列。
3. 加载预训练的词向量
